#!/usr/bin/env bash
# The generated override include — the last config-file in the managed block,
# which is the only position that beats a theme — and the preset sidecar that
# does the same job for a saved preset. Sourced by lib/menu.sh; not run directly.

_override_file_path() { echo "$STUDIO_DIR/generated/explicit-overrides.conf"; }

_write_override_header() {
  local out="$1" mode="${2:-active}" summary
  if [ "$mode" = "preset" ]; then
    summary="$(t "由 ghostty-config-studio 產生，重新儲存這個預設時會自動重寫。" \
      "Generated by ghostty-config-studio; rewritten automatically whenever this preset is re-saved.")"
  else
    summary="$(t "由 ghostty-config-studio 產生，套用選擇時會自動重寫。" \
      "Generated by ghostty-config-studio; rewritten automatically on every apply.")"
  fi
  {
    echo "# $summary"
    echo "# $(t "Ghostty 會讓後面的 config-file 蓋過父檔的直接指定，所以明確的純量設定要放在最後的 include 才能壓過主題。" \
      "Ghostty lets a later config-file override direct assignments in the parent file, so explicit scalar settings live in this last include to beat theme values.")"
  } > "$out"
}

# Ghostty lets a later include beat direct assignments, but repeatable keys
# append rather than replace. Hoisting those into the override include would
# change meaning — most visibly by demoting the chosen font to a fallback.
_raw_lines_from_block() {
  [ -f "$GHOSTTY_CONFIG" ] || return 0
  awk -v b="$BEGIN_MARK" -v e="$END_MARK" -v pre="$_PREAMBLE_RE" '
    function excluded(k) {
      return k == "config-file" || k == "custom-shader" || k == "theme" || \
             k == "font-family" || k == "font-family-bold" || \
             k == "font-family-italic" || k == "font-family-bold-italic" || \
             k == "palette" || k == "keybind" || k == "font-feature"
    }
    $0==b {if (!done) inb=1; next}
    $0==e {if (inb) done=1; inb=0; next}
    inb && /^# category:/ { cat=substr($0, 12); next }
    inb && cat != "" {
      if ($0 ~ pre) next
      if (cat != "_overrides") {
        key=$0
        sub(/^[[:space:]]*/, "", key)
        sub(/[[:space:]]*=.*/, "", key)
        if (!excluded(key)) print
      }
      cat=""
    }
  ' "$GHOSTTY_CONFIG"
}

# The include line goes through the environment, not `awk -v`: -v runs escape
# processing over its value, so a backslash anywhere in $STUDIO_DIR came out
# the other side collapsed — `stu\dio` written as `studio`. That is a
# config-file pointing at a path that does not exist, which is the silent
# whole-config fallback this project exists to avoid.
_rewrite_block_with_overrides() {
  local out="$1" include_line="${2:-}"
  GCS_OVERRIDE_LINE="$include_line" \
  awk -v b="$BEGIN_MARK" -v e="$END_MARK" -v tag="# category:_overrides" -v pre="$_PREAMBLE_RE" '
    BEGIN {line=ENVIRON["GCS_OVERRIDE_LINE"]}
    $0==b {print; if (!done) inb=1; next}
    $0==e {
      if (inb && line != "") { print tag; print line }
      print; if (inb) done=1; inb=0; next
    }
    inb {
      if ($0==tag) { skip=1; next }
      if (skip) { if ($0 ~ pre) next; skip=0; next }
      print; next
    }
    { print }
  ' "$GHOSTTY_CONFIG" > "$out"
}

_managed_directives_without_overrides() {
  awk -v b="$BEGIN_MARK" -v e="$END_MARK" '
    $0==b {if (!done) inb=1; next}
    $0==e {if (inb) done=1; inb=0; next}
    inb && $0=="# category:_overrides" { skip=1; next }
    inb && skip { skip=0; next }
    inb && $0 !~ /^# category:/ { print }
  ' "$GHOSTTY_CONFIG"
}

# Keyed on the whole destination path, not just its basename. Two presets named
# the same in different directories used to share one sidecar, so saving the
# second silently rewrote the raw settings the first one applies. cksum rather
# than a hash tool because it is the one that is guaranteed present.
_preset_sidecar_path() {
  local dest="$1" base tag
  base="${dest##*/}"
  base="${base%.conf}"
  tag="$(printf '%s' "$dest" | cksum | awk '{print $1}')"
  echo "$STUDIO_DIR/generated/presets/${base}-${tag}.conf"
}

_sync_overrides() {
  local override_path raw_f cfg_tmp gen_tmp fault rc
  override_path="$(_override_file_path)"
  [ -f "$GHOSTTY_CONFIG" ] || { rm -f "$override_path"; return 0; }
  fault="$(_marker_fault "$GHOSTTY_CONFIG")"
  [ "$fault" = "none" ] && { rm -f "$override_path"; return 0; }
  # A block shape the rewriter cannot represent. Leave both the config and the
  # generated include exactly as they are rather than rewriting half of one.
  # apply_selection refuses these up front, so the only way here is the undo
  # path — where the user is entitled to restore a config this tool would not
  # itself have written, and must not have it silently mangled on the way back.
  [ "$fault" = "ok" ] || return 0

  raw_f="$(mktemp)"
  _raw_lines_from_block > "$raw_f"

  cfg_tmp="$(mktemp)"
  if [ ! -s "$raw_f" ]; then
    _rewrite_block_with_overrides "$cfg_tmp"
    rc=0
    _replace_if_changed "$GHOSTTY_CONFIG" "$cfg_tmp" || rc=1
    rm -f "$raw_f"
    # Only after the reference is gone from the config. Deleting the include
    # first would leave a window where the config points at a file that is not
    # there, and a Ghostty reading it in that window loses the whole config.
    [ "$rc" -eq 0 ] && rm -f "$override_path"
    return "$rc"
  fi

  mkdir -p "${override_path%/*}"
  gen_tmp="$(mktemp)"
  _write_override_header "$gen_tmp" active
  cat "$raw_f" >> "$gen_tmp"
  rm -f "$raw_f"
  # The include file has to exist before the config names it, for the same
  # reason.
  _replace_if_changed "$override_path" "$gen_tmp" || return 1

  _rewrite_block_with_overrides "$cfg_tmp" "config-file = $override_path"
  _replace_if_changed "$GHOSTTY_CONFIG" "$cfg_tmp" || return 1
  return 0
}

# save_current_as DEST — snapshot whatever's currently active (across every
# category: theme/font/cursor/...) into DEST as a standalone preset file.
# Raw scalar lines stay readable in DEST, and when any are present they are
# also restated in a last-applied sidecar include so Ghostty resolves them
# after any theme include inside the preset.
save_current_as() {
  local dest="$1" raw_f dest_tmp sidecar sidecar_tmp
  _require_sane_markers || return 1
  if [ ! -f "$GHOSTTY_CONFIG" ] || [ "$(_marker_fault "$GHOSTTY_CONFIG")" != "ok" ]; then
    t "目前沒有可儲存的選擇，先挑一個主題、字體或游標。" \
      "Nothing currently selected to save — pick a theme, font, or cursor first." >&2
    return 1
  fi
  raw_f="$(mktemp)"
  _raw_lines_from_block > "$raw_f"

  dest_tmp="$(mktemp)"
  _managed_directives_without_overrides > "$dest_tmp"

  if [ -s "$raw_f" ]; then
    sidecar="$(_preset_sidecar_path "$dest")"
    mkdir -p "${sidecar%/*}"
    sidecar_tmp="$(mktemp)"
    _write_override_header "$sidecar_tmp" preset
    cat "$raw_f" >> "$sidecar_tmp"
    _replace_if_changed "$sidecar" "$sidecar_tmp"
    echo "config-file = $sidecar" >> "$dest_tmp"
  fi

  _replace_if_changed "$dest" "$dest_tmp"
  rm -f "$raw_f"
}
